### ISSUE TITLE
Fix A typo as your first pull request :)

### ISSUE THREAD

**Issue by AllanOcelot** [LearnDevelopmentPublic/ReallyAnnoyingDirectory#10]
Hey, you want to try contributing to an open source github project? Then do this super simple issue.

**The Issue:**
Let's make this non difficult - There's a typo in the file 'allanPage.html'. The word 'Button' is mistyped as 'Buttton'. So, find the spelling mistake and fix it!

You can find a guide for how to contribute to github projects, on the main page of this project.

If you need help / do not understand something, find me in the discord under 'NomadAllan'.

Good luck!

**Comment by WebDevMR** [comment]
I'd like to work on this.
