### ISSUE TITLE
A Smooth Compact Dropdown UI that fits into the top left corner of the directory. 

### ISSUE THREAD

**Issue by Tor020** [LearnDevelopmentPublic/ReallyAnnoyingDirectory#18]
Will be used for switching out directory Stylesheets
Should be something like one of these
[ex1](https://codepen.io/Palgie/pen/krglu?page=11 ) [ex2](https://codepen.io/carlcalderon/pen/KhwDH?page=3) [ex3](https://codepen.io/Kallissien/pen/gKuHw?page=5) [ex4](https://codepen.io/Palgie/pen/krglu?page=11) [ex5](https://codepen.io/dope/pen/rCqzL?page=18) [ex6]( https://codepen.io/3cky/pen/uerfm?page=25)

When creating the the UI, Create a new folder to store directory resources in, if a there is not a folder for that purpose already. 

[Part of StyleSheetSwitchingInterface Project](https://github.com/LearnDevelopmentPublic/ReallyAnnoyingDirectory/projects/1)

**Comment by hotborsh** [comment]
Please assign it to me.
