### ISSUE TITLE
- Style Sheet Compact Dropdown Starts off closed but when clicked extends out

### ISSUE THREAD

**Issue by Tor020** [LearnDevelopmentPublic/ReallyAnnoyingDirectory#21]
Part of [StyleSheet Switching Interface Project](https://github.com/LearnDevelopmentPublic/ReallyAnnoyingDirectory/projects/1)

**Comment by hotborsh** [comment]
Please assign it to me.

**Comment by finchMFG** [comment]
@hotborsh I am about to push a PR, but stylesheet selection still isn't live. Are you planning on using JS and the div or switching over to a select + option setup?

**Comment by hotborsh** [comment]
@finchMFD I will use JS and the div.
