### ISSUE TITLE
Invalid "Back to the Directory" links

### ISSUE THREAD

**Issue by johnpiapian** [LearnDevelopmentPublic/ReallyAnnoyingDirectory#99]
Most if not all of the back-to-the-directory links are not working properly; showing page not found error.

**Comment by Tor020** [comment]
Thanks for bringing this up, it's due to a few url migrations. 

I'll look into fixing it and close the issue when it's functioning correctly.

**Comment by Andy-404** [comment]
I want to work on this!

**Comment by Andy-404** [comment]
@Tor020 I want to work on this!

**Comment by Tor020** [comment]
@Andy-404 Sounds good go ahead and submit a PR with the necessary changes when you get the chance. 

Thanks
